# -*- coding: utf-8 -*-
"""Seaborn_and_Linear_Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EJSprHaVLwKP7mhYm0itBW1gdnkTF1lo

# Introduction

Do higher film budgets lead to more box office revenue? Let's find out if there's a relationship using the movie budgets and financial performance data that I've scraped from [the-numbers.com](https://www.the-numbers.com/movie/budgets) on **May 1st, 2018**. 

<img src=https://i.imgur.com/kq7hrEh.png>

# Import Statements
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""# Notebook Presentation"""

pd.options.display.float_format = '{:,.2f}'.format

from pandas.plotting import register_matplotlib_converters
register_matplotlib_converters()

"""# Read the Data"""

data = pd.read_csv('cost_revenue_dirty.csv')

"""# Explore and Clean the Data

**Challenge**: Answer these questions about the dataset:
1. How many rows and columns does the dataset contain?
2. Are there any NaN values present?
3. Are there any duplicate rows?
4. What are the data types of the columns?
"""

data.shape

data.isna().values.any()

data[data.duplicated(['Movie_Title', 'Release_Date']) == True]  # check if there are duplicate rows and find them

data.drop_duplicates(['Movie_Title', 'Release_Date'], inplace = True)
data.duplicated(['Movie_Title', 'Release_Date']).any()  # check if they're removed

data.info()

"""### Data Type Conversions

**Challenge**: Convert the `USD_Production_Budget`, `USD_Worldwide_Gross`, and `USD_Domestic_Gross` columns to a numeric format by removing `$` signs and `,`. 
<br>
<br>
Note that *domestic* in this context refers to the United States.
"""

chars_to_remove = [',', '$']
columns_to_clean = ['USD_Production_Budget', 
                    'USD_Worldwide_Gross',
                    'USD_Domestic_Gross']
 
for col in columns_to_clean:
    for char in chars_to_remove:
        # Replace each character with an empty string
        data[col] = data[col].astype(str).str.replace(char, "")
    # Convert column to a numeric data type
    data[col] = pd.to_numeric(data[col])

"""**Challenge**: Convert the `Release_Date` column to a Pandas Datetime type. """

data.Release_Date = pd.to_datetime(data.Release_Date)

data.info()

"""### Descriptive Statistics

**Challenge**: 

1. What is the average production budget of the films in the data set?
2. What is the average worldwide gross revenue of films?
3. What were the minimums for worldwide and domestic revenue?
4. Are the bottom 25% of films actually profitable or do they lose money?
5. What are the highest production budget and highest worldwide gross revenue of any film?
6. How much revenue did the lowest and highest budget films make?
"""

data.describe()  # this answers all the above questions

"""# Investigating the Zero Revenue Films

**Challenge** How many films grossed $0 domestically (i.e., in the United States)? What were the highest budget films that grossed nothing?
"""

print(f"{len(data[data.USD_Domestic_Gross == 0].values)} films grossed 0$ domestically.")

data[data.USD_Domestic_Gross == 0].sort_values('USD_Production_Budget', ascending=False).head(10)

"""**Challenge**: How many films grossed $0 worldwide? What are the highest budget films that had no revenue internationally?"""

print(f"{len(data[data.USD_Worldwide_Gross == 0].values)} films grossed 0$ worldwide.")

data[data.USD_Worldwide_Gross == 0].sort_values('USD_Production_Budget', ascending=False).head(10)

"""### Filtering on Multiple Conditions"""

international_releases = data.loc[(data.USD_Domestic_Gross == 0) * (data.USD_Worldwide_Gross != 0)]  # movies that made no money in the US but made money worldwide, means they released outside the US
international_releases.shape[0]  # number of entries

"""**Challenge**: Use the [`.query()` function](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.query.html) to accomplish the same thing. Create a subset for international releases that had some worldwide gross revenue, but made zero revenue in the United States. 

Hint: This time you'll have to use the `and` keyword.
"""

international_releases = data.query('USD_Domestic_Gross == 0 and USD_Worldwide_Gross != 0')
international_releases.shape[0]

"""### Unreleased Films

**Challenge**:
* Identify which films were not released yet as of the time of data collection (May 1st, 2018).
* How many films are included in the dataset that have not yet had a chance to be screened in the box office? 
* Create another DataFrame called data_clean that does not include these films. 
"""

# Date of Data Collection
scrape_date = pd.Timestamp('2018-5-1')

future_releases = data[data.Release_Date > scrape_date]  # movies that are not yet released

print(f"Number of unreleased movies: {len(future_releases)}")
future_releases

data_clean = data[data.Release_Date <= scrape_date]  # only keep movies released before or on the scrape date
data_clean.sort_values('Release_Date', ascending=False).head()  # check release dates of newest released movies

data_clean.shape[0]  # number of movies released before or on the scrape date

"""### Films that Lost Money

**Challenge**: 
What is the percentage of films where the production costs exceeded the worldwide gross revenue? 
"""

movies_that_lost_money = data_clean[data_clean.USD_Worldwide_Gross < data_clean.USD_Production_Budget]  # movies that cost more to make than they earned

print(f"{round(len(movies_that_lost_money)/len(data_clean) * 100, 2)}% of movies lost money.")

"""
# Seaborn for Data Viz: Bubble Charts"""

plt.figure(figsize=(8,4), dpi=150)

with sns.axes_style('darkgrid'):
  ax = sns.scatterplot(data=data_clean,
                      x='USD_Production_Budget', 
                      y='USD_Worldwide_Gross',
                      hue='USD_Worldwide_Gross', # colour
                      size='USD_Worldwide_Gross',) # dot size
  
  ax.set(ylim=(0, 3000000000),
        xlim=(0, 450000000),
        ylabel='Revenue in $ billions',
        xlabel='Budget in $100 millions',)
 
plt.show()

"""
### Plotting Movie Releases over Time

**Challenge**: Try to create the following Bubble Chart:

<img src=https://i.imgur.com/8fUn9T6.png>

"""

plt.figure(figsize=(8,4), dpi=150)


with sns.axes_style("darkgrid"):
    ax = sns.scatterplot(data=data_clean, 
                    x='Release_Date', 
                    y='USD_Production_Budget',
                    hue='USD_Worldwide_Gross',
                    size='USD_Worldwide_Gross',)
 
    ax.set(ylim=(0, 450000000),
           xlim=(data_clean.Release_Date.min(), data_clean.Release_Date.max()),
           xlabel='Year',
           ylabel='Budget in $100 millions')

"""# Converting Years to Decades Trick

**Challenge**: Create a column in `data_clean` that has the decade of the release. 

<img src=https://i.imgur.com/0VEfagw.png width=650> 

Here's how: 
1. Create a [`DatetimeIndex` object](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DatetimeIndex.html) from the Release_Date column. 
2. Grab all the years from the `DatetimeIndex` object using the `.year` property.
<img src=https://i.imgur.com/5m06Ach.png width=650>
3. Use floor division `//` to convert the year data to the decades of the films.
4. Add the decades as a `Decade` column to the `data_clean` DataFrame.
"""

dt_index = pd.DatetimeIndex(data_clean.Release_Date)
years = dt_index.year

# use floor division to get the year rounded to the nearest 10

years = years // 10  # get rid of the last digit entirely
years = years * 10  # get the last digit we just removed back as a 0

data_clean['Decade'] = years

data_clean.head()

"""### Separate the "old" (before 1969) and "New" (1970s onwards) Films

**Challenge**: Create two new DataFrames: `old_films` and `new_films`
* `old_films` should include all the films before 1969 (up to and including 1969)
* `new_films` should include all the films from 1970 onwards
* How many films were released prior to 1970?
* What was the most expensive film made prior to 1970?
"""

old_films = data_clean[data_clean.Decade <= 1960]
new_films = data_clean[data_clean.Decade > 1960]

len(old_films)

old_films.sort_values('USD_Production_Budget', ascending=False).head(1)  # most expensive movie released pre 1970

"""# Seaborn Regression Plots"""

plt.figure(figsize=(8,4), dpi=150)

with sns.axes_style("whitegrid"):
  ax = sns.regplot(data=old_films, 
            x='USD_Production_Budget', 
            y='USD_Worldwide_Gross',
            scatter_kws = {'alpha': 0.4},
            line_kws = {'color': 'black'})
  
  ax.set(
      xlabel='Budget',
      ylabel='Worldwide Gross'
  )

plt.show()

"""**Challenge**: Use Seaborn's `.regplot()` to show the scatter plot and linear regression line against the `new_films`. 
<br>
<br>
Style the chart

* Put the chart on a `'darkgrid'`.
* Set limits on the axes so that they don't show negative values.
* Label the axes on the plot "Revenue in \$ billions" and "Budget in \$ millions".
* Provide HEX colour codes for the plot and the regression line. Make the dots dark blue (#2f4b7c) and the line orange (#ff7c43).

Interpret the chart

* Do our data points for the new films align better or worse with the linear regression than for our older films?
* Roughly how much would a film with a budget of $150 million make according to the regression line?
"""

plt.figure(figsize=(8,4), dpi=150)

with sns.axes_style('darkgrid'):
  ax = sns.regplot(
      data = new_films,
      x = new_films.USD_Production_Budget,
      y = new_films.USD_Worldwide_Gross,
      color='#2f4b7c',
      scatter_kws = {'alpha': 0.3},
      line_kws = {'color': '#ff7c43'}
  )

  ax.set(
      xlabel='Budget in $ 100 millions',
      ylabel='Revenue in $ billions',
      xlim = (0, new_films.USD_Production_Budget.max()*1.1),
      ylim = (0, new_films.USD_Worldwide_Gross.max()*1.1)
  )

plt.show()

"""# Run Your Own Regression with scikit-learn

$$ REV \hat ENUE = \theta _0 + \theta _1 BUDGET$$
"""

# we used univariate regression above
# this is regression with a single explanatory variable (budget in this case)
# explanatory variables are also called features 
# the y value is known as the response variable or the target
# the slope of the function tells us how much extra revenue we'd get if we increased budget by a certain amount
# the y intercept tells us how much a movie would make with 0 budget


from sklearn.linear_model import LinearRegression

# linear regression object
regression = LinearRegression()

# explanatory variables / features
X = pd.DataFrame(new_films, columns=['USD_Production_Budget'])

# response variable / target
Y = pd.DataFrame(new_films, columns=['USD_Worldwide_Gross'])

# we created new dataframes because LinearRegression objects prefer dataframes over pandas.Series objects
# alternatively, we can use this approach

X = new_films[['USD_Production_Budget']] 
Y = new_films[['USD_Worldwide_Gross']]

# this method works because we are changing the shape of the column from (rows,) to (rows, 1), which is adding a column and turning it into a 2D object by adding double square brackets
# this saves us from creating a new dataframe because all sklearn wants is a 2D object with rows and columns
# can also work with multiple exogenous variables, just do new_films[['USD_Production_Budget', 'USD_Worldwide_Budget']] in this case if you needed both in 1 object

regression.fit(X, Y)  # find the best fit line

regression.intercept_  # y-intercept, theta 0

regression.coef_  # slope, theta 1

regression.score(X,Y)  # R-Squared, this is the percentage of the variance our model can explain, eg: here, we can explain nearly 56% of the variance in the data, that is amazing for a straight line

"""**Challenge**: Run a linear regression for the `old_films`. Calculate the intercept, slope and r-squared. How much of the variance in movie revenue does the linear model explain in this case?"""

old_film_regression = LinearRegression()

X = old_films[['USD_Production_Budget']]
Y = old_films[['USD_Worldwide_Gross']]

old_film_regression.fit(X,Y)

print(f"Slope: {old_film_regression.intercept_}\nY-intercept: {old_film_regression.coef_}\nR-squared: {old_film_regression.score(X,Y)}")

"""# Use Your Model to Make a Prediction

We just estimated the slope and intercept! Remember that our Linear Model has the following form:

$$ REV \hat ENUE = \theta _0 + \theta _1 BUDGET$$

**Challenge**:  How much global revenue does our model estimate for a film with a budget of $350 million? 
"""

budget = 350000000
revenue_estimate = regression.intercept_[0] + (regression.coef_[0,0]*budget)
revenue_estimate = round(revenue_estimate, -6)

f"A movie with a budget of $350M is predicted to make around ${str(revenue_estimate)[0:4]}M."